In [6]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [76]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.preprocessing import StandardScaler
from imblearn.ensemble import EasyEnsembleClassifier

# Read the CSV and Perform Basic Data Cleaning

In [9]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [12]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [13]:
# preprocessing

loans_binary_encoded = pd.get_dummies(df, columns=["home_ownership", "verification_status","pymnt_plan", "initial_list_status",  "application_type", "hardship_flag", "debt_settlement_flag", "issue_d", "next_pymnt_d" ])
loans_binary_encoded.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N,issue_d_Feb-2019,issue_d_Jan-2019,issue_d_Mar-2019,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
0,10500.0,0.1719,375.35,66000.0,low_risk,27.24,0.0,0.0,8.0,0.0,...,1,1,0,1,1,0,0,1,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,20.23,0.0,0.0,17.0,1.0,...,1,1,0,1,1,0,0,1,0,1
2,20000.0,0.2000,529.88,56000.0,low_risk,24.26,0.0,0.0,8.0,0.0,...,1,1,0,1,1,0,0,1,0,1
3,10000.0,0.1640,353.55,92000.0,low_risk,31.44,0.0,1.0,10.0,1.0,...,1,1,0,1,1,0,0,1,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,18.76,0.0,1.0,14.0,0.0,...,1,1,0,1,1,0,0,1,0,1

In [14]:
# Create our features
X = loans_binary_encoded.drop(columns='loan_status')

# Create our target
y = loans_binary_encoded['loan_status']

In [15]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N,issue_d_Feb-2019,issue_d_Jan-2019,issue_d_Mar-2019,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.0,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.876121,0.860340,0.139660,1.0,1.0,0.371696,0.451066,0.177238,0.383161,0.616839
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.329446,0.346637,0.346637,0.0,0.0,0.483261,0.497603,0.381873,0.486161,0.486161
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,1.000000,1.000000,0.000000,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.000000,1.000000,0.000000,1.0,1.0,0.000000,0.000000,0.000000,0.000000,1.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,1.000000,0.000000,1.0,1.0,1.000000,1.000000,0.000000,1.000000,1.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.0,1.0,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({'low_risk': 51366, 'high_risk': 246})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [69]:
# Resample the training data with the BalancedRandomForestClassifier
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Create a random forest classifier.
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fitting the model
brf_model = brf.fit(X_train_scaled, y_train)

In [70]:
# Making predictions using the testing data.
predictions = brf.predict(X_test_scaled)

predictions

array(['low_risk', 'high_risk', 'low_risk', ..., 'low_risk', 'high_risk',
       'low_risk'], dtype=object)

In [72]:
# Calculated the balanced accuracy score
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

acc_score

0.8744551002615518

In [71]:
# Display the confusion matrix
# Calculating the confusion matrix.
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

cm

array([[   70,    31],
       [ 2129, 14975]])

In [73]:
# Print the imbalanced classification report
# Displaying results
print("Confusion Matrix")
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix
Accuracy Score : 0.8744551002615518
Classification Report
              precision    recall  f1-score   support

   high_risk       0.03      0.69      0.06       101
    low_risk       1.00      0.88      0.93     17104

    accuracy                           0.87     17205
   macro avg       0.51      0.78      0.50     17205
weighted avg       0.99      0.87      0.93     17205

In [75]:
# List the features sorted in descending order by feature importance
# Calculate feature importance in the Random Forest model.
importances = brf_model.feature_importances_

# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.07744793691712648, 'total_pymnt_inv'),
 (0.06601165005416255, 'last_pymnt_amnt'),
 (0.06166524392373963, 'total_rec_int'),
 (0.059773576313426974, 'total_rec_prncp'),
 (0.058715483643557595, 'total_pymnt'),
 (0.02365418178538414, 'installment'),
 (0.022534294084143695, 'out_prncp_inv'),
 (0.01987840504870664, 'out_prncp'),
 (0.01741583115504387, 'dti'),
 (0.01617838665196858, 'max_bal_bc'),
 (0.01562161922063628, 'mo_sin_old_rev_tl_op'),
 (0.015033907806150382, 'total_bal_ex_mort'),
 (0.015008240829307462, 'mo_sin_old_il_acct'),
 (0.014945633836578457, 'total_bal_il'),
 (0.014250672239571636, 'avg_cur_bal'),
 (0.014244708537682676, 'total_rev_hi_lim'),
 (0.013741139831911633, 'loan_amnt'),
 (0.013610967570313317, 'bc_open_to_buy'),
 (0.013529741514372206, 'revol_bal'),
 (0.013517493772408896, 'tot_cur_bal'),
 (0.013304165713955601, 'il_util'),
 (0.012914446957319067, 'total_rec_late_fee'),
 (0.012910789655192278, 'annual_inc'),
 (0.012904388025430638, 'total_il_high_credit_limit'),
 (0.012853773900967978, 'int_rate'),
 (0.012826043520586949, 'total_bc_limit'),
 (0.012812135869712471, 'total_acc'),
 (0.012605589467222575, 'tot_hi_cred_lim'),
 (0.012521046229684012, 'mths_since_rcnt_il'),
 (0.011939100336027632, 'mths_since_recent_bc'),
 (0.011863134499416148, 'bc_util'),
 (0.010589852778980991, 'all_util'),
 (0.010575748850639655, 'num_il_tl'),
 (0.010215938055943754, 'open_acc'),
 (0.010186500911781735, 'mths_since_recent_inq'),
 (0.009626935233713014, 'num_rev_accts'),
 (0.00886431139958643, 'acc_open_past_24mths'),
 (0.008790345001275396, 'issue_d_Mar-2019'),
 (0.008712768081006439, 'mo_sin_rcnt_tl'),
 (0.00866171408683979, 'mo_sin_rcnt_rev_tl_op'),
 (0.008485099893286755, 'total_cu_tl'),
 (0.008467234298824528, 'num_actv_bc_tl'),
 (0.008384954177959009, 'inq_last_12m'),
 (0.008249478090123294, 'num_bc_tl'),
 (0.008164788205717763, 'pct_tl_nvr_dlq'),
 (0.007938465904609346, 'open_il_24m'),
 (0.007825956616635573, 'num_bc_sats'),
 (0.007717364481993489, 'num_sats'),
 (0.007494766835832508, 'open_rv_24m'),
 (0.007155452750715795, 'num_op_rev_tl'),
 (0.007062621280538921, 'percent_bc_gt_75'),
 (0.007052671869214383, 'num_actv_rev_tl'),
 (0.006441315915490742, 'mort_acc'),
 (0.006399801550638268, 'issue_d_Feb-2019'),
 (0.006329310707283205, 'open_act_il'),
 (0.006228436863577387, 'num_tl_op_past_12m'),
 (0.006228416471353697, 'num_rev_tl_bal_gt_0'),
 (0.0060690827824258185, 'open_acc_6m'),
 (0.00565573066473115, 'open_rv_12m'),
 (0.005547118134367237, 'tot_coll_amt'),
 (0.00551363858808119, 'next_pymnt_d_May-2019'),
 (0.00531785606129917, 'issue_d_Jan-2019'),
 (0.005085861828773694, 'inq_fi'),
 (0.004593882885753922, 'open_il_12m'),
 (0.004257036275456559, 'inq_last_6mths'),
 (0.004136749855181715, 'next_pymnt_d_Apr-2019'),
 (0.003956410921192906, 'delinq_2yrs'),
 (0.002930237281406079, 'pub_rec_bankruptcies'),
 (0.002914131636258481, 'num_accts_ever_120_pd'),
 (0.0027616275091552683, 'pub_rec'),
 (0.002523188896896911, 'application_type_Joint App'),
 (0.0023444726164398855, 'verification_status_Source Verified'),
 (0.0023094422796882974, 'verification_status_Verified'),
 (0.002306778175685438, 'application_type_Individual'),
 (0.002158692449145814, 'home_ownership_RENT'),
 (0.0020951069171859823, 'verification_status_Not Verified'),
 (0.001940863333853701, 'home_ownership_MORTGAGE'),
 (0.0015606603709715278, 'home_ownership_OWN'),
 (0.0012735121490794969, 'initial_list_status_w'),
 (0.0012562934423076349, 'num_tl_90g_dpd_24m'),
 (0.001115029202469121, 'collections_12_mths_ex_med'),
 (0.0010581041651540955, 'initial_list_status_f'),
 (0.0009373072645007517, 'home_ownership_ANY'),
 (0.000297205087267866, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [80]:
# Train the EasyEnsembleClassifier
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)

eec.fit(X_train, y_train) 
y_pred = eec.predict(X_test)

In [16]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

0.9316600714093861

In [84]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[   93     8]
 [  942 16162]]

In [18]:
# Print the imbalanced classification report
# YOUR CODE HERE

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205